services:
  - type: web
    name: new-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: SQL_DSN
        value: ""
      - key: INITIAL_ROOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Shanghai
      - key: TIKTOKEN_CACHE_DIR
        value: /tmp/tiktoken_cache
